EMS/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path  
from Events.views import(
    about_page, contact_page, home_page, landing_page, login, signup ,admin_login, admin_booking
    ) 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', home_page, name='home'),
    path('about/', about_page, name='about-page'),
    path('contact/', contact_page, name='contact-page'),
    path('', landing_page),
    path('login/', login, name='login'),
    path('signup/', signup, name='signup'),
    path('Events/', include('Events.urls', namespace='Events')),
    path('about/', about_page, name='about'),
    path('contact/', contact_page, name='contact'),
    path('admin_login/',admin_login,name='admin-login'),
    path('admin_booking/',admin_booking,name='admin-booking')
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
  

Events/urls.py
from django.urls import path
from .views import event_delete, event_list, create_event, book_ticket, update_event, event_detail

app_name = "Events"

urlpatterns = [
    path('eventlist/',event_list, name='event-list'),
    path('create_event/',create_event, name='create-event'),
    path('ticket/',book_ticket, name='book-ticket' ),
    path('<int:pk>/update_event/', update_event, name='update-event'),
    path('<int:pk>/event_detail/',event_detail, name='event-detail'),
    path('<int:pk>/delete/', event_delete, name='event-delete')
]

Events/models.py
from django.db import models

class User(models.Model):
    name = models.CharField(max_length=20, unique=True)
    email = models.CharField(max_length=40)
    gender = models.CharField(max_length=6)
    password = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.name}"

class Admin(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=40)
    password = models.CharField(max_length=10)

    def __str__(self):
        return f"{self.name}"

class Event(models.Model):
    name = models.CharField(max_length=20)
    time = models.TimeField()
    date = models.DateField()
    duration = models.PositiveIntegerField()
    description = models.CharField(max_length=50)
    coordinator = models.CharField(max_length=20)
    max_participants = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.name}"

class Book_Ticket(models.Model):
    first_name = models.CharField(max_length=20,)
    last_name = models.CharField(max_length=20)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    phone = models.PositiveBigIntegerField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


    

Events/forms.py
from django import forms
from django.forms import DateInput, EmailInput, NumberInput, PasswordInput, Select, TextInput, TimeInput
from .models import Admin, Event, Book_Ticket, User

class EventModelForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['name','time','date','duration','description','coordinator','max_participants']
        widgets = {
            'name':TextInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Name'}),
            'time':TimeInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Time'}),
            'date':DateInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Date'}),
            'duration':NumberInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Duration'}),
            'description':TextInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Description'}),
            'coordinator':TextInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Coordinator'}),
            'max_participants':NumberInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Max_Participants'}),        
        }

class TicketModelForm(forms.ModelForm):
    class Meta:
        model = Book_Ticket
        fields = ['first_name', 'last_name', 'event','phone']
        widgets = {
            'first_name':TextInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'First Name'}),
            'last_name':TextInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Last Name'}),
            'event':Select(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Event'}),
            'phone':NumberInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Number'})
        }

class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['name','email','gender','password']
        widgets = {
            'name':TextInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Name'}),
            'email':EmailInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Mail'}),
            'gender':Select(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Gender'}),
            'password':PasswordInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Enter Password'}),
        }

class AdminCreationForm(forms.ModelForm):
    class Meta:
        model:Admin
        fields = ['name','email','password']
        widgets = {
            'name':TextInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Name'}),
            'email':EmailInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Mail'}),
            'password':PasswordInput(attrs={'class': "form-control",'style': 'max-width: 300px;','placeholder': 'Enter Password'})

        }

Events/views.py
from .models import Admin, Event
from django.shortcuts import  HttpResponseRedirect, render, redirect

from Events.forms import EventModelForm, TicketModelForm, UserCreationForm, Book_Ticket, AdminCreationForm


#User Landing Page
def landing_page(request):
    return render(request, 'landing_page.html')

#User Home Page
def home_page(request):
    return render(request,'home_page.html')

#User About Page
def about_page(request):
    return render(request,'about_page.html')

#User Contact Page  
def contact_page(request):
    return render(request,'contact_page.html')

def login(request):
     form = UserCreationForm()    
     if request.method =="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("home_page.html")
     context ={
        "form": form
    }
     return render(request, 'Registration/login.html', context)


def signup(request):
    form = UserCreationForm()    
    if request.method =="POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Registration/login.html")
    context ={
        "form": form
    }
    return render(request, 'Registration/signup.html', context)

def event_list(request):
    Events = Event.objects.all()
    context ={
        "Events":Events
    }
    return render(request, 'Events/event_list.html', context)


def event_detail(request, pk):
    event = Event.objects.get(id=pk)
    event.time = event.time.strftime('%H:%M:%S')
    context = {
       "Event":event
    }
    return render(request, 'Events/event_detail.html', context)


def book_ticket(request):
    form = TicketModelForm()    
    if request.method =="POST":
        form = TicketModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Events:event-list")
    context ={
        "form": form
    }
    return render(request, 'Events/book_ticket.html', context)


def create_event(request):
    form = EventModelForm()
    if request.method =="POST":
        form = EventModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Events:event-list")
    context ={
        "form": form
    }
    return render(request, 'Events/create_event.html', context)


def update_event(request, pk):
    context ={}
    event = Event.objects.get(id=pk)
    form = EventModelForm(request.POST or None, instance = event)

    # save the data from the form and
    # redirect to detail_view
  
    if form.is_valid():
        form.save()
        return redirect("Events:event-detail"+pk)
    context["form"] = form
    return render(request, "Events/update_event.html", context)

    #   form = EventModelForm(instance=Event)
    #   if request.method =="POST":
    #     form = EventModelForm(request.POST, instance=Event)
    #     if form.is_valid():
    #         form.save()
    #         return redirect("Events:event-list"+pk) 
    #   context = {
    #     "form": form,
    #     "Events": event       
    # } 
    #   return render(request, "Events/update_event.html", context) 


def event_delete(request,pk):
    context ={}
    event = Event.objects.get(id=pk)
    form = EventModelForm()
    if request.method =="POST":
            event.delete()
    if form.is_valid():
        form.save()
        return redirect("Events:event-list")
    context["form"] = form   
    return render(request, 'Events/event_delete.html',context)
   

# Admin Page

def admin_login(request):
    if request.method =="POST":
        form = AdminCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("admin_home.html")
    context ={}
    return render(request,'admin_login.html', context)

#Admin View Bookings

def admin_booking(request):
    if request.method =="POST":
        form = AdminCreationForm(request.POST)
        if form.is_valid():
            form.save()
    context ={}
    return render(request,'admin_booking.html', context)
    

# def admin_booking(request):
#     if request.session =="POST":
#         booking = Book_Ticket.objects.all()
#         data = {'booking':booking}
#         return render(request,'admin_booking.html',context=data)
       
#     else:
#         data = {'status':'You need to login first'}
#         return render(request,'admin_login.html',context=data)

Events/templates/Events/book_ticket.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with LeadMark landing page.">
    <meta name="author" content="Devcrud">
    <title>TICKETS</title>
    
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
        rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
</head>

<body>
    <style>
        body{
            background-repeat: no-repeat;
            background-size: cover;
            background-image: url({% static 'img/event/pic 8.jpg' %});
        }
    </style>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Header Section Begin -->
    <header class="header-section">
        <div class="container">
            <div class="logo">
                <a href="#">
                    <img src="{% static 'img/logo 3.jpg' %}" alt="" style="height: 100px; max-height: 150px; width:8cm;">
                </a>
            </div>
            <div class="nav-menu">
                <nav class="mainmenu mobile-menu">
                    <ul>
                        <li class="active"><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'about' %}  ">About</a></li>
                        <li><a href="#">Schedule</a></li>
                        <li><a href="{% url 'contact' %}">Contacts</a></li>
                    </ul>
                </nav>
                <a href="#" class="primary-btn top-btn"><i class="fa fa-ticket"></i>Ticket</a>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Header End -->

    <!-- Page Header -->
        <center><header class="header">
        <div class="overlay">
        <div class="box">
          <u><h2>Book Your Tickets</h2></u>&nbsp;
          <form method="post" action=".">
              {% csrf_token %}
              <div class="form-group">
                  <b>First Name:<br></b>
                  {{ form.first_name }}
              </div>
      
              <div class="form-group">
              <b>Last Name:<br></b>
                  {{ form.first_name }}
              </div>
            
              <div class="form-group">
              <b>Event :<br></b>
                  {{ form.event }}
      
              </div>
              
              <div class="form-group">
              <b>Phone:<br></b>
                     <input type="tel" name="phone" id="Phone" pattern="+91 xxxx-nnnnnn" placeholder="+91 xxxx-nnnnnn">
              </div><br>
      
              <div class="form-group">
                  <button type="submit" class="btn btn-primary">Submit</button>
                  <button onclick="history.back()">Back</button>
                </div>
          </form>
        </div>
    </header></center>
    <!-- End Of Page Header -->
  <!-- Js Plugins -->
  <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'js/jquery.slicknav.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>

</body>
</html>









    

Events/templates/Events/create_event.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with LeadMark landing page.">
    <meta name="author" content="Devcrud">
    <title>CREATE EVENT</title>
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
    rel="stylesheet">
   <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">


   <!-- Css Styles -->
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
   <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
   <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
   <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
   <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
   <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
   <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">

<body>
    <style>
        body{
            background-repeat: no-repeat;
            background-size: cover;
            background-image: url({% static 'img/event/pic 9.jpg' %});
        }
    </style>

    <!-- Page Preloder -->
    <div id="preloder">
      <div class="loader"></div>
  </div>

  <!-- Header Section Begin -->
  <header class="header-section">
      <div class="container">
          <div class="logo">
              <a href="#">
                  <img src="{% static 'img/logo 3.jpg' %}" alt="" style="height: 100px; max-height: 150px; width:8cm;">
              </a>
          </div>
          <div class="nav-menu">
              <nav class="mainmenu mobile-menu">
                  <ul>
                      <li class="active"><a href="{% url 'home' %}">Home</a></li>
                      <li><a href="{% url 'about' %}  ">About</a></li>
                      <li><a href="#">Schedule</a></li>
                      <li><a href="#">Blog</a></li>
                      <li><a href="{% url 'contact' %}">Contacts</a></li>
                  </ul>
              </nav>
              <a href="#" class="primary-btn top-btn"><i class="fa fa-ticket"></i> Ticket</a>
          </div>
          <div id="mobile-menu-wrap"></div>
      </div>
  </header>
    <!-- End Of Header Section Begin -->

    <!-- Page Header -->
    <header class="header">
        <div class="overlay">  
        <title>Create New Event</title>
    <center><u><b><h1 style="font-family: Arial, Helvetica, sans-serif;">Add Event</h1></b></u>
<form method="post" action="." style="font-size:small;">
      {% csrf_token %}
        <br><div class = "form-group">
        <b>Name:</b><br>
          {{ form.name }}
        </div>

        <div class = "form-group"> 
        <b>Time:</b><br>
          <input type="time" name="time" min="6:00" max="18:00" class="form-control"  style="max-width: 300px;" placeholder="Time" required="" id="id_time">
        </div>

        <div class = "form-group">
        <b>Date:<br></b>
          <input type="date" name="date" class="form-control" style="max-width: 300px;" placeholder="Time" required="" id="id_date">
        </div>

        <div class = "form-group">
        <b>Duration:<br></b>
          {{ form.duration }}
        </div>

        <div class = "form-group">
        <b>Description:<br></b>
          <textarea id="description" name="description"  placeholder="Description"  rows="4" cols="50"></textarea>
        </div>

        <div class = "form-group">
          <b>Coordinator:<br></b>
          {{ form.coordinator }}
        </div>

        <div class = "form-group">
          <b>Max_Participants:<br></b>
          {{ form.max_participants }}
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-primary">Save</button> &nbsp; 
          <a href="javascript: history.back()" type="button" class="btn btn-info" style="background-color: white; color: #000;">Go back</a>
          <div id="wrap"></div>
        </div>
  </form></center>
        </div>  
    </header>
    <!-- End Of Page Header -->
	
    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

Events/templates/Events/event_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with LeadMark landing page.">
    <meta name="author" content="Devcrud">
    <title>Delete Event</title>
     <!-- Google Font -->
     <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
     rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">
 
 
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
 </head>
 <body>
     <style>
         body{
             background-repeat: no-repeat;
             background-size: cover;
             background-image: url({% static 'img/event/pic 9.jpg' %});
         }
     </style>
 
   <!-- Page Preloder -->
     <div id="preloder">
         <div class="loader"></div>
     </div>
 
     <!-- Header Section Begin -->
     <header class="header-section">
         <div class="container">
             <div class="logo">
                 <a href="#">
                     <img src="{% static 'img/logo 3.jpg' %}" alt="" style="height: 100px; max-height: 150px; width:8cm;">
                 </a>
             </div>
             <div class="nav-menu">
                 <nav class="mainmenu mobile-menu">
                     <ul>
                         <li class="active"><a href="{% url 'home' %}">Home</a></li>
                         <li><a href="{% url 'about' %}  ">About</a></li>
                         <li><a href="#">Schedule</a></li>
                         <li><a href="#">Blog</a></li>
                         <li><a href="{% url 'contact' %}">Contacts</a></li>
                     </ul>
                 </nav>
                 <a href="#" class="primary-btn top-btn"><i class="fa fa-ticket"></i> Ticket</a>
             </div>
             <div id="mobile-menu-wrap"></div>
         </div>
     </header>
     <!-- End Of Second Navigation -->

    <!-- Page Header -->
    <header class="header">
        <div class="overlay">
          <h4><b>Are You Sure You Want to Delete This Event?</b></h4>  
          <form method="post" action=".">
              {% csrf_token %}             
                <div class="form-group">
                  <button><a href="/Events/eventlist/">Submit</button></a>
                </div>
          </form>          
    </header>
    <!-- End Of Page Header -->
	
    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
    <script src="{% static 'js/jquery.slicknav.js' %}"></script>
    <script src="{% static 'js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

</body>
</html>

Events/templates/Events/update_event.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Start your development with LeadMark landing page.">
    <meta name="author" content="Devcrud">
    <title>Event Updation</title>
          <!-- Google Font -->
      <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500,600,700,800,900&display=swap"
      rel="stylesheet">
     <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap" rel="stylesheet">
  
  
     <!-- Css Styles -->
     <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">
     <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  </head>
  <body>
      <style>
          body{
              background-repeat: no-repeat;
              background-size: cover;
              background-image: url({% static 'img/event/pic 9.jpg' %});
          }
      </style>
  
    <!-- Page Preloder -->
      <div id="preloder">
          <div class="loader"></div>
      </div>
  
      <!-- Header Section Begin -->
      <header class="header-section">
          <div class="container">
              <div class="logo">
                  <a href="#">
                      <img src="{% static 'img/logo 3.jpg' %}" alt="" style="height: 100px; max-height: 150px; width:8cm;">
                  </a>
              </div>
              <div class="nav-menu">
                  <nav class="mainmenu mobile-menu">
                      <ul>
                          <li class="active"><a href="{% url 'home' %}">Home</a></li>
                          <li><a href="{% url 'about' %}  ">About</a></li>
                          <li><a href="#">Schedule</a></li>
                          <li><a href="#">Blog</a></li>
                          <li><a href="{% url 'contact' %}">Contacts</a></li>
                      </ul>
                  </nav>
                  <a href="#" class="primary-btn top-btn"><i class="fa fa-ticket"></i> Ticket</a>
              </div>
              <div id="mobile-menu-wrap"></div>
          </div>
      </header>
      <!-- End of Header Section Begin -->

  <!-- Page Header -->
  <header class="header">
      <div class="overlay">
          <form method="post" action="." style="font-size:small;">
          <center><b><u><h1 class="head">Manage Events</h1></u></b>
            {% csrf_token %}
              <br><div class="form-group">
               <b>Name :<br></b>
               <input type="text" name="name" autocomplete="off" value="{{ Event.name }}" required>
              </div>

              <div class = "form-group"> 
               <b>Time :<br></b>
               <input type="time" name="time" min="6:00" max="18:00" class="form-control"  style="max-width: 300px;" placeholder="Time" required="" id="id_time">
              </div>
             
              <div class = "form-group">
                <b>Date :<br></b>
                <input type="date" name="date" class="form-control" style="max-width: 300px;" placeholder="Time" required="" id="id_date">
              </div>
              
              <div class = "form-group">
                <b>Duration :<br></b>
                {{ form.duration }}
              </div>
              
              <div class = "form-group">
                <b>Description :<br></b>
                <textarea id="description" name="description" value="{{ Event.description }}"  placeholder="Description"  rows="4" cols="50"></textarea>
              </div>
              
              <div class = "form-group">
                <b>Coordinator :<br></b>
                <input type="text" name="coordinator" autocomplete="off" value="{{ Event.coordinator }}" required><br>
              </div>
    
              <div class = "form-group">
                <b>Max_Participants :<br></b>
                {{ form.max_participants }}
              </div>

              <div class="form-group">
               <button type="submit" class="btn btn-primary">Reset</button>
               <button type="submit" class="btn btn-primary">Submit</button>
               <button type="submit" class="btn btn-primary">Delete</button> 
               <button onclick="history.back()">Back</button>
              </div></center>
          </form>
  </header> 
    <!-- End Of Page Header -->
	
	  <!-- Js Plugins -->
      <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
      <script src="{% static 'js/jquery.countdown.min.js' %}"></script>
      <script src="{% static 'js/jquery.slicknav.js' %}"></script>
      <script src="{% static 'js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'js/main.js' %}"></script>
  

</body>
</html>